// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZsQnbQf053EEInyXtBh_4XQGua1BwSjM',
    appId: '1:322645695588:web:5975c5ec53415895831371',
    messagingSenderId: '322645695588',
    projectId: 'busya-app-d2dbb',
    authDomain: 'busya-app-d2dbb.firebaseapp.com',
    storageBucket: 'busya-app-d2dbb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwKQHBQA09T5tJ6aBeHXfcveQXPZTeDqY',
    appId: '1:322645695588:android:e472bbdfe41ffa71831371',
    messagingSenderId: '322645695588',
    projectId: 'busya-app-d2dbb',
    storageBucket: 'busya-app-d2dbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDylU5C_CfgcdkzHzeBC9hZtsW2JVDYHsY',
    appId: '1:322645695588:ios:088edbf5a45cd722831371',
    messagingSenderId: '322645695588',
    projectId: 'busya-app-d2dbb',
    storageBucket: 'busya-app-d2dbb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
